Added option for build timeout
arcalot/arcaflow-plugin-image-builder pull request #35
Opened 2022-12-12 20:49 UTC by jaredoconnell

## Changes introduced with this PR

This change is required because there is a chance that the build will take longer than 5 minutes on github actions (due to the fewer computational resources granted to workflows). In those cases, the build fails.
It is important now because the recent changes to the template, which were moved to the other repos, added more stages with dnf installs, which added minutes to the build.

I set the default to 10 minutes.

The way I did this adds an option, and packs some related options into a struct. It is probably a better practice to do this than let the config go deep into the program, or use an excessive amount of params.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

2022-12-13 13:49 UTC, dustinblack reviewed
AFAICT this looks sane, but I don't know the code well enough to dig in deeply, and I'm not sure how to functionally test this.

2022-12-13 14:27 UTC, jaredoconnell commented
> AFAICT this looks sane, but I don't know the code well enough to dig in deeply, and I'm not sure how to functionally test this.

Good point. I just added some instructions on how to test it in the PR comment.

2022-12-13 22:19 UTC, portante approved these changes
The code changes seem fine, but I have not verified this works as advertised.

2022-12-14 20:25 UTC, mfleader requested changes
Great work @jaredoconnell!

I think it only needs the README to be updated a little.

2022-12-14 22:45 UTC, jaredoconnell commented
> Great work @jaredoconnell!
> 
> I think it only needs the README to be updated a little.

I just added documentation for the new feature. I placed it alongside the features that are from the same config.

2022-12-15 15:43 UTC, mfleader approved these changes

2022-12-15 15:44 UTC, merged